# Dummy corpus for testing

CORPUS = [
    
    {
        "Question":"¿Cómo se dará respuesta a mi petición hecha por formulario?",
        "Answer":"Todas aquellas consultas y peticiones recibidas tanto por formulario, como a través del teléfono, serán respondidas, tan pronto como sea posible, por correo electrónico. Presta atención por si nuestro mensaje acaba en la bandeja de “Correo no deseado” de tu cuenta de correo."
    },
    {
        "Question":"¿Cuándo se me dará una respuesta sobre mi tramitación en curso?",
        "Answer":"Estamos trabajando lo más rápido posible para dar respuesta a las numerosas peticiones que estamos recibiendo estos días. Si ya has efectuado tu petición rellenando un formulario a través de la web, responderemos tu solicitud atendiendo por orden de fecha de salida. Si tienes una reserva aérea, por favor, ten en cuenta que el plazo aproximado de respuesta por parte de las aerolíneas puede llegar a ser de 6 a 12 meses desde el momento en que se les traslada la solicitud de reembolso."
    },
    {
        "Question":"No he recibido respuesta a la solicitud realizada a través del formulario",
        "Answer":"Tras rellenar el formulario de nuestra web para realizar una consulta o solicitud, deberías recibir un e-mail de confirmación. Procura verificar que no ha terminado en la carpeta de “Correo no deseado”. Si no lo recibes, pero nuestra web te informó de que la petición había sido recibida con éxito tras rellenar y enviar el formulario, seguro que tu petición habrá quedado registrada igualmente. Nos pondremos en contacto contigo."
    },
    {
        "Question":"¿Cómo puedo gestionar mi cancelación o cambios de fechas si mi reserva es con una compañía Low-cost?",
        "Answer":"En caso de cancelación o cambio de fechas en reservas de vuelos con aerolíneas low-cost, debes contactar directamente con la aerolínea para que te informen de las opciones disponibles y cómo proceder. En caso de que te corresponda el reembolso, reenvíanos a e_commerce@viajeseci.es la comunicación que te hará llegar la aerolínea, para que después pueda ser efectuado al mismo medio de pago utilizado en la compra tras verificarlo. Sin embargo, para cambios o cancelaciones en reservas de vuelos de las aerolíneas Ryanair o Wizzair, debes rellenar el formulario correspondiente a través de nuestra web."
    },
    {
        "Question":"Tengo un seguro contratado. ¿Qué incluye?",
        "Answer":"Puedes consultar la documentación de los seguros disponibles en el apartado de “Seguros” de las Condiciones Generales de Viajes El Corte Inglés."
    },
    {
        "Question":"He realizado la reserva en una oficina física pero esta se encuentra temporalmente cerrada, ¿a quién me puedo dirigir?",
        "Answer":"Aunque algunas delegaciones se encuentran cerradas, existe personal gestionando las reservas y atendiendo las peticiones. Rellena el formulario de la web indicando la delegación donde se realizó la reserva y nos pondremos en contacto contigo."
    },
    {
        "Question":"¿Qué es la PSD2 y cómo me afecta?",
        "Answer":"La PSD2 es la nueva directiva europea que regula la prestación de los servicios de pago y transacciones de pago electrónicas. Fue traspuesta a la legislación de España por el Real Decreto Ley 19/2018, de 23 de noviembre, de servicios de pago y otras medidas urgentes en materia financiera. En Viajes El Corte Inglés afecta a las compras pagadas con Tarjeta Bancaria o Paypal.Entre los principales objetivos de la PSD2 se encuentran la mejora de la seguridad online y el refuerzo de la protección contra fraudes en las operaciones bancarias realizadas a través de internet.Entre las principales medidas de seguridad está la aplicación obligatoria de la Autenticación Reforzada del Cliente del comercio (SCA – Strong Customer Authentication) en todas las compras de comercio electrónico a partir del 1 de enero de 2021, siempre que no se aplique alguna de las exenciones previstas en la norma. Esta autenticación reforzada obliga a aplicar 2 factores a elegir entre: una cosa que el usuario conoce (por ejemplo, la contraseña), una que posee (por ejemplo, el móvil) y otra que es (por ejemplo, la huella dactilar o el rostro). Ya no valdrá con el primero como hasta ahora, sino que serán necesarios 2 (doble autenticación o SCA)El proceso de compra segura dependerá del banco emisor, pudiendo consistir en el código que recibas con SMS + un segundo factor, o la validación a través de la App de tu banco. Por favor, consulta la operativa en tu banco para estar preparado antes de realizar tus próximas compras.La PSD2 no afecta a las compras realizadas con Tarjeta de Compra de El Corte Inglés, Línea de Crédito, Tarjeta Regalo o abono, , por lo que el proceso de compra no se verá modificado."
    },
    {
        "Question":"¿Con cuánta antelación he de presentarme en el aeropuerto?",
        "Answer":"Deberás presentarte en los mostradores de facturación de la compañía aérea con tiempo suficiente, siempre teniendo en cuenta los diferentes tiempos de espera de los mostradores, los controles de seguridad, las posibles distancias entre las puertas de embarque, etc.Como normal general, se recomienda a los pasajeros que se presenten en el mostrador de facturación con una hora y media de antelación en el caso de vuelos nacionales, y al menos dos horas y media en caso de vuelos internacionales, siempre teniendo en cuenta las indicaciones anteriormente citadas.Por regla general, cuenta con que las compañías aéreas suelen cerrar el embarque 40 minutos antes de la salida del vuelo, denegando la entrada a cualquier pasajero a partir de ese momento."
    },
    {
        "Question":"¿Cómo recibo mi billete de avión después de la compra?",
        "Answer":"Al efectuar tu compra de billetes de avión, recibes un “billete electrónico”, es decir, una modalidad de billete que no requiere el envío físico de documentación. Tras efectuar la compra te indicaremos el localizador de tu reserva, que deberás presentar en el mostrador de la compañía aérea en el aeropuerto, junto con tu DNI/pasaporte, el día de salida de tu vuelo. Para tu comodidad, tras la compra, te enviaremos un e-mail a la dirección de correo electrónico que nos hayas indicado recogiendo los detalles de tu reserva junto con el localizador.Recuerda que también deberás realizar el check-in de tu vuelo directamente con la aerolínea. La mayoría de las compañías lo permiten entre 24 y 2 horas antes de la salida del vuelo, bien a través de su página web, sin moverte de casa, o bien directamente en el aeropuerto. En caso de duda, verifica el plazo directamente con la aerolínea. Para tu comodidad, Viajes El Corte Inglés te facilita los enlaces de las compañías aéreas en el apartado “Auto check-in” para que puedas obtener las tarjetas de embarque desde tu ordenador. De esta manera podrás ahorrar las largas colas de los mostradores de facturación, así como seleccionar tu asiento si la compañía aérea te ofrece esa posibilidad. No obstante, recuerda que esto no te exime de pasar por el mostrador de la compañía aérea en caso de facturar una o más maletas, por lo que te recomendamos que, en cualquier caso, observes siempre los tiempos de antelación correspondientes. Puede suceder que la compañía aérea no haya habilitado la función de check-in online a través de su página web para determinadas rutas aéreas, por lo que, en ese caso, deberás hacerlo directamente en el aeropuerto."
    },
    {
        "Question":"¿Qué documentación debo llevar para el vuelo?",
        "Answer":"Las compañías aéreas exigen la presentación del DNI o Pasaporte a todos los pasajeros y en todos los vuelos para verificar la identidad de los viajeros. El documento necesario depende de la ruta: Si vas a volar entre destinos dentro de España o a un país perteneciente al territorio de Schengen necesitas el DNI o el pasaporte. Para el resto de destinos internacionales necesitarás el pasaporte. Recuerda llevar también el localizador de la reserva que recibirás al realizar la compra. Los menores también deberán viajar convenientemente identificados y debidamente autorizados, por lo que se ruega consultar la recomendación de viajes con menores en  www.maec.es. La documentación se te pedirá tanto en los mostradores de facturación como en las puertas de embarque. Recuerda que es tu responsabilidad informarte previamente y cumplir con los requisitos necesarios para realizar el viaje y entrar en el país de destino (pasaporte, visado, vacunas, o inclusive presentar el billete del vuelo de regreso en caso de adquirir sólo el de ida, etc), no teniendo derecho a ningún tipo de reembolso en caso de denegarte el embarque por no cumplir los requisitos exigidos. Consulta las condiciones necesarias para viajar en: www.maec.es En caso de tratarse de una reserva bonificada por “familia numerosa”, “residentes” deberás verificar que dispones de la documentación oficial correspondiente, que deberá ser presentada en el momento de recoger el billete en la agencia de viajes (si procede), en el momento de la facturación en el aeropuerto, y previo al embarque junto con la documentación personal de cada viajero (DNI, Pasaporte, certificado de empadronamiento para bonificación de transporte, visado, etc.)."
    },
    {
        "Question":"¿Qué hago si el nombre de un pasajero supera el máximo de caracteres?",
        "Answer":"Las compañías aéreas exigen que los nombres y apellidos de los pasajeros sean reflejados en la reserva exactamente cómo aparecen en el DNI o pasaporte, pero algunas de ellas aplican un número máximo de caracteres que no se debe superar. Si durante el proceso de compra, la aerolínea seleccionada impone un número máximo de caracteres, te avisaremos y, si tu nombre y apellidos lo superan, no utilices abreviaturas ni manipules los nombres, pues la compañía podría denegarte el embarque por razones de seguridad. En su lugar, efectúa tu reserva en cualquier agencia de Viajes El Corte Inglés donde nuestros agentes confirmarán la reserva con total seguridad."
    },
    {
        "Question":"¿Cuántos kilos de equipaje puedo llevar en el vuelo?",
        "Answer":"Como norma general en los vuelos las franquicias de equipaje oscilan entre unos 20kg y 23 kg por pasajero. Confirma la franquicia de equipaje directamente con la aerolínea para una información más exhaustiva.  En los vuelos low cost o de bajo coste, te aconsejamos consultar directamente la normativa de la propia compañía aérea, ya que en la mayoría de los casos el equipaje no está incluido en el precio del billete.Equipaje de mano: Por motivos de seguridad aérea, únicamente está permitido subir en cabina una pieza de mano por persona, y recuerda que algunas compañías pueden obligarte a entregar el equipaje de mano en el momento de subir al avión para transportarlo en la bodega.Como norma general, el peso máximo permitido para el equipaje de mano es de 6kg-10kg, dependiendo de la franquicia de equipaje de la compañía aérea; y sus medidas no deben exceder de los 55cm x 40cm x 20cm. No obstante, siempre aconsejamos que esta información se re-confirme con la propia compañía aérea, ya que tanto el peso como las medidas específicas pueden variar en cada caso."
    },
    {
        "Question":"¿Qué incluye el precio del vuelo?",
        "Answer":"El precio del vuelo incluye:• Las tasas de aeropuerto.• El precio base de la reserva, es decir, el precio del vuelo marcado por la compañía aérea.En el momento de efectuar tu reserva y en función de la tarifa seleccionada, te informaremos de si tu billete incluye la facturación de una maleta o si ésta es de coste adicional."
    },
    {
        "Question":"¿Es necesario confirmar el horario del viaje antes de la salida del vuelo?",
        "Answer":"EN RESERVAS DE LÍNEA REGULAR:Debes saber que Viajes El Corte Inglés dispone de un departamento exclusivo de tramitación de cambios horarios para vuelos de línea regular que se pondrá en contacto contigo a través de e-mail para informarte de las modificaciones eventualmente efectuadas por las compañías aéreas y que puedan afectarte. En caso de no estar conforme con el cambio realizado, recibirás en el mismo correo electrónico otras opciones disponibles.Es importante tener en cuenta que este departamento únicamente responde vía correo electrónico, por lo que deberás responder sobre ese mismo correo electrónico: cambioshorariosweb@viajeseci.esEN RESERVAS CON COMPAÑÍAS LOW-COST O DE BAJO COSTE:Si has efectuado reserva con una compañía low cost o de bajo coste, tu vuelo debe de ser confirmado directamente con la compañía low cost entre 24 y 48 horas antes de salida del vuelo ya que puede sufrir modificaciones. Es importante tener en cuenta que este tipo de vuelos pueden verse obligados a realizar cambios en el último momento, y no ser avisados con tiempo suficiente."
    },
    {
        "Question":"¿Cuál es la política de cancelación y modificación de reservas de vuelo?",
        "Answer":"La política de cambios y cancelaciones de reservas de Viajes El Corte Inglés está indicada en las Condiciones Generales  que tienes siempre disponibles. Además, también podrás consultarlas, antes de confirmar tu reserva, en las condiciones que verás durante el proceso de compra de vuelos.No obstante, puedes contratar el seguro de viajes PREMIUM que además de las coberturas de viaje cubre los gastos de cancelación y modificación de Viajes El Corte Inglés y los gastos de anulación del proveedor hasta un máximo de 600€. Más información y condiciones en el apartado “Seguros de viaje” que encontrarás en nuestras Condiciones Generales.Para realizar cambios o cancelaciones llama a nuestro Contact Center – Asistencia. Ten en cuenta que en el caso de haber seleccionado la opción \"recogida en delegación\" deberás contactar con la oficina donde hayas posicionado la reserva."
    },
    {
        "Question": "¿Puedo elegir mi asiento en la reserva?",
        "Answer":"Por norma general, sí es posible seleccionar asiento en vuelos de línea regular hasta 24 o 48 horas antes de la salida. Sin embargo, existen circunstancias en las que no es posible como, por ejemplo, si así se establece en las condiciones de la tarifa que hayas seleccionado o cuando se trata de vuelos operados por una aerolínea distinta. La selección se puede realizar durante el check-in de la propia aerolínea con el localizador de la reserva que te enviamos tras la compra de tus billetes. Para más información, consulta nuestra página de check-in: http://www.viajeselcorteingles.es/auto-checkin.htmlSi no fuera posible la selección de asiento, consulta directamente con la aerolínea contactando telefónicamente o a través de sus mostradores en el aeropuerto."
    },
    {
        "Question":"¿Puedo reservar con el descuento de residente balear/canario o el de Ceuta y Melilla?",
        "Answer":"Nuestra página web te permite reservar online billetes de línea regular con descuento residente. Para ello, simplemente marca la casilla de “Residentes” al efectuar tu búsqueda de vuelos, y los precios se mostrarán con el descuento aplicado en los casos en que las compañías y los vuelos lo permitan. A partir de ese momento, tendremos tu consentimiento para realizar la verificación de tu condición de residente a través del Sistema de Acreditación de Residencia Automatizado (SARA). Tras la emisión de tu reserva, el sistema te indicará si tu residencia ha sido verificada o no.MUY IMPORTANTE: Debemos tener en cuenta que si el resultado de la comprobación es “No Verificado” se te ofrecerá la opción de reintentar tu verificación. Si el resultado del reintento fuera “Verificado”, no necesitarás aportar tu acreditación de residencia en el aeropuerto. Si, por el contrario, el resultado fuera nuevamente “No verificado”, tendrás que identificarte y acreditar tu condición de beneficiario en la facturación o en el embarque mediante el \"certificado de empadronamiento para bonificación de transporte\" expedido por el ayuntamiento correspondiente. En caso contrario, la compañía aérea podrá denegarte el embarque o cobrarte la tarifa vigente sin aplicar el descuento de residente.Generalmente, no es posible efectuar reservas con aerolíneas low-cost aplicando el descuento de residente."
    },

    {
        "Question":"¿Quién se considera menor y qué documentación debe llevar?",
        "Answer":"EN COMPAÑÍAS DE LÍNEA REGULAR:Para las compañías de línea regular, un menor es la persona que no ha cumplido los 18 años de edad en la fecha del vuelo.Bebé: Es el menor que en la fecha del vuelo aún no ha cumplido los 2 años de edad. Viaja sin ocupar asiento, acompañados de una persona mayor de 18 años, pagando un porcentaje variable de la tarifa del adulto.Niño: Es el menor que habiendo cumplido los 2 años de edad, no ha cumplido los 12 años en la fecha del vuelo y viaja siempre acompañado de una persona mayor de 18 años. Viaja ocupando asiento, abonando un porcentaje variable de la tarifa del adulto.Joven: Es el menor que habiendo cumplido los 12 años de edad, no ha cumplido los 18 años en la fecha del vuelo y viaja sin acompañante, y/o con asistencia en vuelo si fuese necesario. Viaja abonando tarifa de adulto.EN COMPAÑÍAS LOW-COST:Por lo general, las aerolíneas consideran menor a cualquier persona que no ha cumplido los 18 años de edad en la fecha del vuelo y establecen intervalos de edades para considerar a los pasajeros bebés, niños, jóvenes, etc. No obstante, pueden variar en función de la aerolínea, por lo que, en caso de duda, deberás consultar previamente.SOBRE LA DOCUMENTACIÓN A LLEVAR:En viajes nacionales: Los menores deben viajar siempre debidamente documentados con su DNI/pasaporte.En viajes internacionales: Se recomienda, con carácter general, que siempre que viaje un menor solo, acompañado por un único progenitor o por terceras personas, se observen las siguientes condiciones:Llevar consigo la autorización expresa, en su caso, de los padres, del progenitor ausente o de quien ejerza legalmente la patria potestad.Portar los documentos de viaje ordinarios (pasaporte o Documento Nacional de Identidad, en su caso)Llevar consigo la documentación que pruebe la filiación y patria potestad según el caso y el país de destino.La exigencia en cuanto al tipo de autorización y las circunstancias en que es requerida esta documentación es muy variable según el país de destino y su legislación y costumbres locales. En caso de duda, es conveniente consultar con la Embajada o Consulado del país de destino."
    },
    {
        "Question":"¿Cómo puedo solicitar menores no acompañados?",
        "Answer":"Las compañías aéreas contemplan distintas formas de efectuar esta clase de reservas con menores no acompañados y, de hecho, no todas ofrecen este servicio. Por esta razón, siempre que necesites efectuar una reserva con menores no acompañados deberás dirigirte con suficiente antelación a tu agencia de Viajes El Corte Inglés donde nuestros agentes efectuarán tu reserva con total seguridad. Algunas compañías requieren que sea el cliente directamente quién realice la solicitud, en cuyo caso, nuestros agentes te lo indicarán para que puedas completar la reserva. Recuerda que el servicio de menores no acompañados debe solicitarse con antelación suficiente, preferiblemente varios días antes de la salida de tu vuelo, y que puede conllevar el pago de un suplemento que difiere en función de la aerolínea con la que vas a volar. Nuestros agentes te informarán de su importe en el momento de la reserva, así como de su forma de pago. Los menores sin acompañar serán aceptados siempre que cumplan los siguientes requisitos:    • Que la solicitud de asistencia para un menor durante el vuelo haya sido confirmada por parte de la compañía aérea con anterioridad.    • Que una persona adulta acompañe al menor al aeropuerto de salida, realice los trámites necesarios para el embarque del mismo, presente el oportuno descargo de responsabilidad, y espere hasta el despegue del avión.    • Cuando el viaje requiera parada-estancia (con interrupción programada del viaje), será necesario que una persona adulta reciba y acompañe al menor en estas escalas, encargándose de los trámites necesarios para su reembarque y esperar hasta el despegue del avión. Este punto dependerá de la ruta, de la compañía que opere los vuelos, y del tipo de paradas realizadas durante el trayecto.    • Que un adulto se haga cargo del menor y esté presente en el aeropuerto de llegada a la hora prevista de aterrizaje del vuelo, identificándose al personal de la compañía para la recepción del menor."
    },
    {
        "Question":"¿Qué condiciones existen para solicitar menores no acompañados?",
        "Answer": "Los menores no acompañados no serán aceptados en vuelos con código compartido, es decir, aquellos vuelos que no estén operados únicamente por la propia compañía área. Las compañías aéreas aceptarán en cada vuelo un número máximo de menores no acompañados y con asistencia en el vuelo confirmada con antelación. Esta limitación dependerá de cada compañía área. No es posible solicitar asistencia para menores de 5 años sin cumplir, y tampoco serán aceptados en un vuelo sin ser acompañados por un adulto. Para menores entre 12 y 18 años que vuelen solos a destinos internacionales, también habrá que solicitar asistencia, y/o una petición especial de aceptación en dichos vuelos si la asistencia no fuese necesaria.NOTA IMPORTANTE EN CASO DE COMPAÑÍAS LOW COST: Recuerda que la normativa interna de las compañías aéreas de bajo coste obliga a que todos los menores de 14 años vuelen siempre acompañados por un adulto y debidamente documentados con DNI y/o pasaporte. Si no se cumplen estos requisitos, a estos menores de 14 años se les denegará el embarque a los vuelos englobados dentro de compañías low-cost.Algunas compañías aéreas, entre las que se incluyen las de bajo coste, no ofrecen el servicio de asistencia a menores de 14 años."
    },
    {
        "Question":"¿Qué debo tener en cuenta al volar con una compañía low-cost o de bajo coste?",
        "Answer":"Si realizas una reserva de vuelo con una aerolínea de las denominadas low-cost o de bajo coste, como por ejemplo Easyjet, Vueling, Ryanair, etc., deberás tener en cuenta las siguientes circunstancias:Estas reservas requieren que realices el check-in online y presentes la tarjeta de embarque impresa en el aeropuerto. En caso de no presentar la tarjeta de embarque impresa, la aerolínea podrá aplicar un suplemento por esta tramitación. Cualquier trámite de cancelación o cambio deberá ser realizado por el pasajero o titular de la reserva contactando directamente con la aerolínea.Estas reservas no permiten ser posicionadas en agencia física de Viajes El Corte Inglés, por lo que deberán ser abonadas íntegramente durante el proceso de reserva online. Además, este tipo de reservas no se pueden financiar.Además, recuerda que la normativa interna de las compañías aéreas de bajo coste obliga a que todos los menores de 14 años vuelen siempre acompañados por un adulto y debidamente documentados con DNI y/o pasaporte. Si no se cumplen estos requisitos, a estos menores de 14 años se les denegará el embarque a los vuelos englobados dentro de compañías low-cost. Algunas compañías aéreas entre las que se incluyen las de bajo coste no ofrecen el servicio de asistencia a menores de 14 años.Recuerda consultar directamente con la compañía aérea sus condiciones de equipaje tales como las medidas máximas de las maletas o sus pesos máximos autorizados."
    },
    {
        "Question":"¿Qué debo tener en cuenta al viajar a Estados Unidos?",
        "Answer": "Si vas a viajar a Estados Unidos, debes obtener previamente una autorización de viaje electrónica a través de ESTA (sistema electrónico para la autorización de viaje) antes de embarcar en un transporte para viajar por aire o mar hacia EEUU.El sitio web de ESTA es:https://esta.cbp.dhs.govCompleta en línea el formulario de solicitud en inglés con al menos 72 horas de antelación al viaje. En la mayoría de los casos recibirás respuesta a los pocos segundos, como autorización aprobada, viaje no autorizado o autorización pendiente. Si necesitas más información, visita: http://www.CBP.gov/travelAdemás, en los vuelos dentro, desde o hacia Estados Unidos, existe la prohibición establecida por el US DOT (Department of Transportation) de llevar, tanto en equipaje facturado como en cabina, productos considerados como peligrosos. Se consideran productos peligrosos:    • Baterías de litio de un tamaño grande y en gran cantidad    • Explosivos/Fuegos artificiales    • Fluidos para cargar mecheros    • Cerillas    • Botellas de Oxígeno/Oxígeno líquido    • Líquidos inflamables    • Pesticidas/Venenos    • Sustancias corrosivasEn caso de duda, recuerda revisar el listado actualizado de productos peligrosos.Por último, asegúrate de que los dispositivos electrónicos que lleves en tu equipaje de mano tengan las baterías cargadas y se encuentren en buen estado.Recuerda que Estados Unidos no es el único país que exige la obtención previa de una autorización de viaje. Infórmate de la documentación necesaria para tu destino consultando la web: www.maec.es "
    },
    {
        "Question":"¿Qué sucede si al finalizar mi reserva veo dos localizadores?",
        "Answer":"En ocasiones, nuestra web puede realizar una reserva de dos vuelos “sólo ida” de distintas aerolíneas como si fueran un vuelo de “ida y vuelta”, aunque realmente se trata de dos reservas independientes y cada una de ellas aplica sus propias condiciones. Nuestra web te informa de ello durante el proceso de compra y, a la finalización de la reserva, te indica el localizador de cada uno de los vuelos por separado.NOTA IMPORTANTE:Si una de esas dos reservas corresponde a una aerolínea de las denominadas “low-cost” (Ryanair, Easyjet, etc.) y necesitaras cancelarla o modificarla, deberás realizar la solicitud contactando directamente con la aerolínea “low-cost”. Los cambios/cancelaciones en la reserva correspondiente a la compañía de línea regular puedes realizarlos llamando a nuestro Contact Center – Asistencia."
    },
    {
        "Question":"¿Qué significa “Precio final desde el primer paso”?",
        "Answer": "En Viajes El Corte Inglés presumimos de ofrecerte siempre el “precio final desde el primer paso”, lo que significa que en cuanto eliges tu vuelo en la pantalla de resultado de búsqueda, nuestro sistema te presentará a continuación el importe final de tu reserva incluyendo cualquier concepto adicional necesario para la misma (tales como los cargos de emisión). Otras agencias de viajes juegan a ocultarte estos cargos y otros adicionales hasta el último momento de tu reserva incrementando el importe final y a menudo compensando al alza cualquier descuento que te hayan podido aplicar previamente. En Viajes El Corte Inglés, al contrario, creemos en una política de precios transparente y honesta que permita a nuestros clientes localizar y comparar de forma rápida, práctica y sencilla nuestros precios. Reservar tu vuelo en www.viajeselcorteingles.es es hacerlo ¡sin sorpresas!"
    },{
        "Question":"¿Puedo usar el tramo de vuelta de un billete de ida y vuelta si no he utilizado el de ida?",
        "Answer":"La mayor parte de las compañías aéreas, si no realizas el vuelo de ida (no te presentas), cancelan automáticamente la vuelta, impidiendo su uso y aplicando las condiciones de cancelación en caso de no presentación."
    },{
        "Question":"¿Puedo añadir a mi reserva servicios adicionales como llevar mascotas, sillas de ruedas, etc. si se trata de un vuelo operado por otra aerolínea?",
        "Answer":"Aquellas reservas realizadas con una aerolínea distinta a la que opera el vuelo no admiten la inclusión de servicios adicionales. En este caso, consulta la posibilidad de contratar estos servicios directamente con la aerolínea."
    },{
        "Question":"¿Cómo puedo financiar mi billete de avión?",
        "Answer":"Si deseas financiar el pago de tu reserva de vuelos deberás efectuar la reserva en la web con tu Tarjeta de Compra El Corte Inglés. Las opciones de financiación, como los plazos, dependerán del importe de tu compra, considerando que existe una cuota mínima mensual que se indicará en la web durante el proceso de compra. También te informaremos, antes de realizar la compra, de las condiciones detalladas de financiación a las que la operación quedará sujeta.Recuerda, esta “Fórmula personal de financiación” es solo para clientes con Tarjeta de Compra El Corte Inglés. Toda la financiación publicitada en esta página es ofrecida por Financiera El Corte Inglés E.F.C., S.A. y está sujeta a su aprobación. Consulta condiciones en https://www.viajeselcorteingles.es/financiacion-onlineNo obstante, debes tener en cuenta que no es posible financiar la compra de billetes de avión de aerolíneas low-cost."
    },{
        "Question":"¿Qué documentación debo llevar al crucero?",
        "Answer":"Recuerda que debes presentar a tu llegada la documentación del crucero que nuestro Contact Center – Venta Telefónica te habrá hecho llegar previamente por correo electrónico. Dependiendo de la naviera con la que realices tu crucero, recibirás la documentación entre 1 y 2 semanas antes de la salida del barco. Además, para embarcar en todos los cruceros es necesario estar en posesión del pasaporte en vigor (con una validez mínima de seis meses desde la fecha de finalización del viaje), así como la documentación necesaria para entrar en los países en los que se realizan escalas. Infórmate previamente de la documentación de entrada necesaria para cada país que vayas a visitar, pues algunos pueden requerir incluso la gestión previa de un visado de entrada cuya documentación deberás llevar también contigo. MUY IMPORTANTE:Queda bajo tu responsabilidad obtener los visados correspondientes. En algunas ocasiones será la propia naviera quien te los facilitará, pero no siempre, por lo que deberás informarte. Del mismo modo, es importante tener en cuenta las formalidades de inmigración en las aduanas ya que varían si la entrada en un país es por vía aérea, terrestre o marítima, por lo que se requiere que el pasaporte tenga una vigencia mínima de 6 meses contados a partir de la fecha de regreso del crucero.Los niños y bebés también deben de llevar su propio pasaporte.MUY IMPORTANTE:El nombre y apellidos indicados en la reserva deben coincidir exactamente con los que aparecen en el pasaporte, así como el lugar, fecha de nacimiento, nacionalidad y número de pasaporte. Recuerda que la más mínima variación podría suponer la denegación del embarque y que cualquier modificación de estos datos una vez reconfirmado el crucero puede conllevar gastos de modificación y/o cancelación."
    },{
        "Question":"¿Qué restricciones de edad tienen los cruceros?",
        "Answer":"La mayoría de navieras exigen una edad mínima de 6 meses en el momento del embarque, aunque ciertos itinerarios por el Caribe y Sudamérica pueden requerir una edad mínima de 12 meses. Recuerda que se puede denegar el embarque a aquellas personas que no cumplan estos requisitos. En caso de duda, consulta con nuestro Contact Center - Venta Telefónica antes de efectuar tu reserva."
    },{
        "Question":"¿Debo dar propinas en el crucero?",
        "Answer":"La propina o “cuota de servicio” es una norma establecida de forma generalizada y obligatoria en todos los cruceros. Las cantidades estipuladas varían en función de la naviera, aunque suelen estar comprendidas entre 10 y 15 euros por persona y día. Por norma general, esta cantidad se entrega la última noche del crucero, aunque también es posible que sea cargada directamente en la tarjeta al realizar el check-out.Esta información es muy general dado que cada naviera puede marcar su propia política por lo que te rogamos que consultes con nuestro Contact Center - Venta Telefónica la política la naviera con la que vas a efectuar tu reserva."
    },{
        "Question":"¿Qué equipaje puedo llevar a mi crucero?",
        "Answer":"La mayoría de las navieras no aplican restricciones de equipaje, aunque se recomienda ajustar el mismo a una maleta de unos 20 a 23kg de peso. Recuerda que no se pueden llevar objetos eléctricos que produzcan calor tipo plancha de pelo, Samsung Galaxy 7 Notes, transformadores eléctricos, etc. No obstante, si tu reserva incluye billetes de avión, tu equipaje deberá cumplir también con la política de equipaje de la/s aerolínea/s con la/s que vayas a volar, así como con la franquicia concreta incluida en la tarifa con la que se efectúe la reserva. Esta limitación puede afectar al peso y número máximo de maletas, sus dimensiones físicas, etc. En caso de superar la franquicia estipulada, la aerolínea podría aplicar un recargo. Está permitido llevar en cabina, como equipaje de mano, una bolsa cuyo peso y dimensiones máximas establece cada compañía y en la que deberán observarse las medidas de seguridad en los aeropuertos, que restringen la cantidad de líquidos o sustancias de consistencia similar que los pasajeros pueden llevar consigo."
    },{
        "Question":"¿Cómo puedo pagar los gastos a bordo durante mi crucero?",
        "Answer":"En el precio de los cruceros casi todo está incluido, pero al igual que ocurre en un hotel, no lo están los extras tales como las llamadas telefónicas, las bebidas, servicios de masajes, etc. Todos estos extras tienen diferentes formas de pago según las compañías, pero en general, en los barcos no se maneja moneda, salvo en el casino y para algunas máquinas recreativas. Un sistema de pagos muy extendido en los cruceros es el de la Tarjeta del Crucero que se entrega con la documentación al comienzo del mismo. Además de servir para abrir el camarote y permitir el desembarque y embarque en cada puerto, en ella se van realizando todos los cargos a bordo. Al embarcar, el pasajero facilita una tarjeta de crédito (no se aceptan de débito) para ir cargando los gastos a bordo y por cada compra que se realice a lo largo del crucero se entregará un justificante. El último día se pasa por caja y se paga todo lo cargado (en la moneda oficial a bordo), pudiéndose abonar con una tarjeta de crédito (no débito) como Visa, American Express, etc., que es la fórmula más usual (se recomienda llevar una), o en metálico, normalmente en dólares o euros. Algunos cruceros ofrecen como alternativa realizar un depósito inicial para los gastos a bordo. Aunque todas las navieras suelen contar con métodos similares de pago a bordo, estos pueden diferir entre compañías, por lo que deberás informarte de su funcionamiento al realizar el embarque.  Si necesitas más detalles, consulta con nuestros asesores qué moneda llevar durante el viaje."
    },{
        "Question":"¿Cuál es el idioma oficial a bordo?",
        "Answer":"El idioma oficial a bordo de un crucero depende de la naviera. Por nombrar algunas de las más habituales:Si viajas con Pullmantur, el idioma oficial a bordo es el castellano.Si viajas con Costa Cruceros o MSC, los idiomas utilizados son el italiano, el inglés, el francés y el alemán, además de asistencia en español.Si viajas con NCL, Royal Caribbean, Celebrity Cruises o Carnival, el idioma oficial a bordo será el inglés. La mayoría de los cruceros que transcurren por el Mediterráneo tienen asistencia en español para todos los pasajeros. En general, suele consistir en una versión resumida del Diario de A Bordo, principales anuncios por megafonía, menús en el restaurante principal, y ciertas excursiones en español. No obstante, puede variar según la naviera, por lo que te rogamos que consultes con nuestro Contact Center - Venta Telefónica."
    },{
        "Question": "¿Cómo se realiza el check-in online?",
        "Answer": "El check-in online es un trámite necesario para poder preparar la documentación de tu crucero. Puedes realizarlo tú mismo directamente en la web de la naviera o, si lo deseas, nuestros agentes pueden hacerlo por ti con un coste de 20€ por persona (solicítalo por e-mail escribiendo a: documentacionback@viajeseci.es). El check-in online se realiza en la página web de la naviera, accediendo mediante el localizador de tu reserva y tus datos personales. Recuerda introducir todos los datos conforme aparecen en tu pasaporte prestando atención a las mayúsculas, minúsculas, espacios, etc. Requisitos habituales para poder realizar el check-in online: Deben incluirse los nombres completos de todos los pasajeros, así como sus fechas de nacimiento y nacionalidad, tal cual figuran en su pasaporte.Debe introducirse una dirección y teléfonos de contacto.Todos los pasajeros deben disponer de pasaporte (puede haber excepciones, consúltanos)No obstante, recuerda que estos requisitos pueden variar según la naviera, por lo que no dudes en informarte en cada caso."
    },{
        "Question":"¿Debo etiquetar mi equipaje?",
        "Answer":"Sí, tu equipaje debe ser identificado usando las etiquetas de maletas que te enviaremos junto a la documentación de tu crucero."
    },{
        "Question":"¿Cómo se realiza el embarque?",
        "Answer":"Antes de poder embarcar deberás realizar una serie de trámites en el puerto, por lo que deberás llegar entre 3 y 4 horas antes de la hora de salida del barco. Allí realizarás, entre otras cosas, la facturación del equipaje, identificando tu maleta con el camarote en el que te vas a alojar. El equipaje se entrega a los maleteros de la estación marítima, quienes se encargarán de trasladarlo a bordo. El personal del barco se encarga de subir a las cabinas el equipaje de tal modo que los pasajeros se lo encontrarán dentro de su camarote o en las puertas del mismo un tiempo después de haber embarcado.Mientras, los pasajeros tienen que realizar el check-in y el control de pasaportes en la estación marítima. El procedimiento es muy similar al del check-in de un aeropuerto. Una vez pasados los controles de pasaporte (se suele pasar uno al hacer el check-in y otro en la pasarela), se puede acceder al barco. Normalmente se entregan los pasaportes al Jefe de Sobrecargo, que te lo devolverá, según la compañía, o al final del crucero, o una vez comprobado al principio del mismo.Una vez embarcados, os acompañará a vuestro camarote una persona de la tripulación, que os presentará a quien será vuestro/a camarero/a de camarote, esto es, la persona que estará a tu servicio durante toda la travesía. A veces, si hay muchas personas embarcando al mismo tiempo, simplemente os darán las instrucciones necesarias para llegar a nuestro camarote por vuestra cuenta.Lo más habitual es que a tu llegada al camarote encuentres el llamado “Diario de a bordo”. Se trata de un pequeño documento que recoge los principales eventos programados a bordo para que puedas planificarte y así disfrutar de todos los espectáculos y actividades que te interesen.  También te recomendamos que pases por el restaurante para poder planificar o reconfirmar tu turno de comidas y cenas, así como por la “Oficina de información” para consultar cómo funciona la “cuenta de a bordo”, es decir, la cuenta donde se irán cargando tus compras y gastos adicionales realizados a bordo durante el crucero.¡AH! Y no olvides que antes de zarpar se realizará un simulacro de evacuación como medida de seguridad obligatoria."
    },{
        "Question":"¿Cómo es la vestimenta a bordo?",
        "Answer":"La vestimenta habitual a bordo de los cruceros es más bien informal, ropa cómoda de sport, aunque esto depende del tipo de barco, estación del año y, por supuesto, la temperatura media de la zona por la que se va a navegar. Sin embargo, durante las noches, es habitual que las navieras ofrezcan actividades como la “Cena del Capitán” u otros eventos temáticos que pueden requerir una vestimenta más formal: Chaquetas para los caballeros y vestidos para las señoras. En estas ocasiones, el capitán saluda a todos los pasajeros y esto implica que sean un poco más protocolarias. De todas formas, en el Diario de A Bordo suele figurar el código de vestimenta recomendado para cada día.En los cruceros por el Mediterráneo y el Caribe conviene llevar ropa ligera y algo de entretiempo para protegerse de los cambios de temperatura y para disfrutar de los paseos nocturnos por cubierta. Es aconsejable llevar traje de baño y calzado con suela de goma para acceder a la piscina y a cubierta. Para cruceros por el norte de Europa se recomienda ropa de entretiempo con alguna prenda de abrigo y gabardina. Por último, recuerda que en las navieras de gama más alta puede existir un código de vestimenta más estricto y, por lo general, más elegante. También debes tener en cuenta que durante las excursiones que realices en tierra es posible que se requiera de una vestimenta más formal en caso de visitar, por ejemplo, templos religiosos. Lo más habitual es que se exija llevar cubiertos los hombros y se prohíban tanto las faldas como los pantalones cortos."
    },{
        "Question":"¿Cuándo debo contratar los paquetes de bebidas, de internet o las excursiones?",
        "Answer":"Reserva con antelación estos servicios para beneficiarte de un precio más ventajoso que contratándolo a bordo, con la seguridad adicional de no quedarte sin disponibilidad. En el caso de las excursiones, recuerda que es habitual que la reserva requiera de hasta 20 días de antelación respecto de la fecha de salida del crucero. Contacta con nosotros para realizar la contratación lo antes posible."
    },{
        "Question":"¿Es necesario contratar un seguro de anulación o seguro médico para mi crucero?",
        "Answer":"En general, no es obligatorio contratar ninguna clase de seguro, aunque desde Viajes El Corte Inglés siempre te recomendamos que cuentes con ellos para disfrutar de tu crucero con total seguridad. Dispones de varias modalidades de seguro que incluyen coberturas en caso de anulación, coberturas para tu equipaje, asistencia médica, etc. En caso de duda, consulta con nuestros agentes para elegir la modalidad que mejor se adapta a tu crucero. No obstante, es posible que algunas ofertas promocionales o destinos requieran, excepcionalmente, la contratación de cierta tipología de seguros para poder efectuar la reserva. Infórmate siempre de las condiciones particulares."
    },{
        "Question":"¿Tengo que vacunarme para viajar en un crucero?",
        "Answer":"Depende de los destinos por los que vayas a navegar. En general, solo los cruceros por el Océano Índico precisan de vacunas especiales, concretamente la vacuna contra la fiebre amarilla. No obstante, te recomendamos que te informes con al menos 8 semanas de antelación sobre las vacunas necesarias para tu crucero consultando con las Delegaciones de Sanidad Exterior competentes en tu comunidad autónoma. "
    },{
        "Question":"¿Qué requisitos de salud debo tener en cuenta para viajar en crucero?",
        "Answer":"Existen algunas circunstancias y requisitos de salud que deberás tener en cuenta a la hora de viajar en crucero: \n En general, las navieras tienen restricciones de embarque para mujeres embarazadas que se encuentren en la semana 24 de embarazo o posterior, aunque depende de cada compañía. Además, hay que tener en cuenta posibles restricciones en caso de que sea necesario utilizar un avión para desplazarse a/desde el puerto de embarque.\n Es importante tener en cuenta circunstancias como la altitud de las zonas que se van a visitar, climatologías, vacunaciones o profilaxis exigidas, en caso de embarazo o padecimiento de determinadas enfermedades crónicas (alteraciones en la presión sanguínea, cardiopatías, etc.)\n Antes de efectuar tu reserva de crucero, consulta siempre las condiciones particulares de la naviera a este respecto y, por supuesto, las recomendaciones de tu médico."
    },{
        "Question":"¿Debo llevar medicamentos?",
        "Answer":"La mayoría de cruceros disponen de un servicio médico y de los medicamentos más habituales y solicitados. Sin embargo, te recomendamos llevar un pequeño botiquín con las medicinas básicas (antigripales, antidiarreicos, analgésicos, antipiréticos, etc.). Si sigues algún tipo de tratamiento especial, recuerda que puede no ser sencillo conseguirlo en el extranjero, por lo que es mejor que lleves suficientes cantidades para la totalidad del viaje. En estos casos, además, es conveniente llevar contigo posibles informes médicos que justifiquen dicho tratamiento, porque algunos medicamentos pueden estar sometidos a restricciones en determinados países. Y ten en cuenta que el Servicio Médico a bordo de los cruceros suele tener un coste adicional elevado, por lo que te recomendamos que lleves contratado un seguro que cubra posibles gastos médicos."
    },{
        "Question":"¿Qué pasa si soy alérgico a alguna comida o necesito alguna comida especial?",
        "Answer":"¡Tranquilo!, ser alérgico a algún alimento no te impedirá disfrutar de tu crucero con total seguridad. La mayoría de las navieras ofrecen opciones especiales para personas alérgicas o con alguna clase de intolerancia alimenticia. Tan solo asegúrate de indicarlo expresamente o dejarlo por escrito en el momento de efectuar la reserva de modo que se disponga de margen para tramitar esta circunstancia con la naviera. No es mala idea recordárselo también al personal de la naviera en recepción, a tu llegada al puerto, de modo que lo tengan presente lo antes posible. Incluso, si lo deseas, puedes pasarte por el comedor del barco y verificar que el maitre lo tiene en cuenta."
    },{
        "Question":"¿Qué otros servicios, incluyendo vuelos, traslados, etc., ofrecen las navieras?",
        "Answer":"Algunas navieras ofrecen paquetes englobando vuelos y traslados (aeropuerto – puerto – aeropuerto).Si vas a necesitar contratar vuelos y/o traslados tanto en el momento de la salida como en el de regreso, te recomendamos que contrates los ofrecidos por la naviera con la que realizas el crucero, en caso de que los ofrezca. De este modo, la naviera estará pendiente de la situación en todo momento y, en caso de demoras, te ofrecerá posibles soluciones. Estos servicios no se tramitan hasta que no se ha confirmado previamente el crucero y están sujetos a disponibilidad por parte de la compañía naviera. Recuerda que esta clase de vuelos no permiten realizar el check-in online al tratarse de vuelos chárter, por lo que obtendrás la tarjeta de embarque en el aeropuerto el día de salida. También hay que tener en cuenta que estos servicios, una vez confirmados, pueden tener hasta un 100% de gastos de cancelación. Además, como en cualquier vuelo, recomendamos consultar antes de la salida por si se han producido modificaciones en los horarios previstos. Otro de los servicios que ofrecen muchas navieras es el llamado “Pack de bebidas”. Contrátalo en el momento de efectuar la reserva si deseas obtener un mejor precio en tus bebidas que abonándolas in situ a bordo. Recuerda informarte previamente sobre las condiciones, como por ejemplo los productos incluidos en el pack."
    },{
        "Question":"¿Existen facilidades a bordo para personas discapacitadas?",
        "Answer":"Es conveniente que estos pasajeros viajen acompañados, aun cuando existen compañías navieras que ofrecen dispositivos especiales a bordo para hacer más confortable su viaje. Recomendamos que, antes de realizar la reserva de tu crucero, contactes con nuestros asesores llamando a nuestro Contact Center - Venta Telefónica para trasladarles tus necesidades. Ellos te informarán detalladamente en cada caso. En cualquier caso, será necesario indicar esta circunstancia a la hora de realizar la reserva con el fin de que se pueda tener margen para tramitarlo con la naviera buscando cabinas adaptadas, próximas a los ascensores o restaurantes, etc. En el caso de personas invidentes, hay que tener en cuenta que la mayoría de navieras no admiten animales domésticos a bordo."
    },{
        "Question":"¿Qué se conoce como “cruceros fluviales”?",
        "Answer":"Los cruceros fluviales son aquellos que transcurren a lo largo de ríos y canales navegables, como por ejemplo el Rhin, el Danubio o el Volga.  Sus barcos son de menor capacidad que los cruceros marítimos (de 65 a 300 pasajeros como máximo) lo que proporciona algunas ventajas muy apreciadas por sus pasajeros. En primer lugar, una menor cantidad de pasajeros se traduce en mejor servicio, más atención por parte de la tripulación y menos aglomeraciones a la hora de realizar embarques y desembarques. Además, los barcos suelen atracar en lugares más céntricos de las ciudades visitadas, lo que permite desplazarse hasta ellas más fácilmente y disfrutar mejor de nuestro tiempo en tierra. Por último, esta clase de cruceros te permitirá disfrutar de unos paisajes y panorámicas únicas a lo largo de su recorrido que son frecuentemente inaccesibles para otros medios de transporte. En cuanto a los demás detalles, no hay grandes diferencias con las características de los cruceros marítimos, más allá de que el menor tamaño de los barcos condiciona el número y tipo de instalaciones, servicios y actividades que se ofrecen a bordo. A nosotros nos gusta explicar que un crucero fluvial es como un circuito en autocar, pero mucho más cómodo, ya que el medio de transporte es, a su vez, el alojamiento."
    },{
        "Question":"¿Cómo funcionan los turnos de comida?",
        "Answer":"Prácticamente en todos los barcos existen 2 turnos de cena (la comida suele contar con un horario muy amplio, ya que suele ofrecerse en el restaurante buffet), variable en función de la naviera:Inicio entre las 18:00h y las 19:30hInicio entre las 20:00h y las 21:30hLos turnos de cena implican que se comparta la mesa asignada con los mismos comensales durante todo el crucero, por eso puedes indicar el turno que deseas al hacer la reserva (aunque no se garantiza su confirmación antes del embarque), ya que las compañías agrupan a los pasajeros por nacionalidades, para que puedan mantener conversaciones en el mismo idioma, etc. Y si viajas en pareja y quieres intimidad, pregunta si el buque cuenta con mesas para dos comensales, al hacer la reserva. Los estrictos horarios de cenas se van liberalizando cada día más en las diferentes compañías. Actualmente, algunas navieras ofrecen la posibilidad de elegir cada noche una mesa y el horario para la cena, el restaurante, etc. A esta opción se le llama “turno libre”."
    },{
        "Question":"¿Cómo se realiza el desembarque?",
        "Answer":"La última noche del crucero, los pasajeros serán debidamente informados en el diario de a bordo de todos los detalles para efectuar el desembarque. El equipaje será depositado la noche anterior al desembarque, a la hora indicada, en la puerta del camarote, correctamente identificado con las etiquetas que previamente encontrará el pasajero en su cabina. A la llegada al puerto, los maleteros procederán a llevar el equipaje a la aduana, donde el cliente se hará cargo del mismo. Quédate contigo un pequeño equipaje de mano con tu documentación personal, dinero y objetos de valor, billetes de tren o avión, y cualquier posible medicamento que puedas necesitar."
    },{
        "Question":"¿Qué tipos de camarotes existen?",
        "Answer":"Existen varios tipos de camarotes que van a determinar el precio del crucero:Interiores: Corresponden normalmente a las categorías inferiores y suelen ser los más económicos. Aunque no disponen de ventana, algunos barcos cuentan con camarotes interiores que dan a un atrio interno. Exteriores: En los barcos más antiguos solían disponer de un ojo de buey para ver el exterior. En los modernos suelen ser ya ventanas más grandes o incluso balcón. Algunos camarotes cuentan con una puerta corrediza transparente que ocupa toda la pared y que da paso a la terraza. Exteriores con vista obstruida: Son aquellas cabinas exteriores que tienen la vista parcial o totalmente limitada por un bote salvavidas, parte del barco o similar. Suites: Con salón, bañera (en algunos con jacuzzi) y, a veces, una pequeña terraza. Son los alojamientos más caros del barco. Las suites suelen alojar a más de dos personas, lo que hace muy populares estos alojamientos entre las familias. "
    },{
        "Question":"¿Qué es un camarote garantizado?",
        "Answer":"Existe un tipo particular de reserva que es la de los camarotes garantizados. En estas reservas, cuyo precio suele ser más ventajoso, el pasajero no elige el número ni la situación del camarote sino que lo hará la naviera en cualquier momento hasta el día del embarque. La reserva garantiza una categoría mínima para el camarote asignado, aunque puede suceder que la naviera asigne finalmente uno de categoría superior sin cargo adicional. No es extraño que muchas de las ofertas especiales de las navieras se realicen en base a este tipo de reservas."
    },{
        "Question":"¿Cómo puedo financiar mi reserva de crucero?",
        "Answer":"Si deseas financiar la compra de tu crucero, recuerda indicarlo durante el proceso de reserva si realizas la confirmación online, o indicárselo a nuestro agente cuando contacte contigo para informarte de tu presupuesto personalizado. En ambos casos, deberás efectuar el pago con la Tarjeta de Compra El Corte Inglés.Las opciones de financiación, como los plazos, dependerán del importe de tu compra, considerando que existe una cuota mínima mensual que se indicará en la web durante el proceso de compra. También te informaremos, antes de realizar la compra, de las condiciones detalladas de financiación a las que la operación quedará sujeta.Recuerda, esta “Fórmula personal de financiación” es solo para clientes con Tarjeta de Compra El Corte Inglés. Consulta condiciones de financiación durante el proceso de compra.Toda la financiación publicitada en esta página es ofrecida por Financiera El Corte Inglés E.F.C., S.A. y está sujeta a su aprobación. Consulta condiciones en https://www.viajeselcorteingles.es/financiacion-online"
    },{
        "Question":"¿Qué documentación debo presentar a mi entrada al hotel?",
        "Answer":"Una vez hayas efectuado tu reserva de hotel recibirás un e-mail con la confirmación de la reserva en la dirección de correo electrónico indicada durante el proceso de compra. En él encontrarás el número de localizador, detalles de todos los servicios contratados y el bono de hotel (voucher) que deberás imprimir y presentar a tu llegada al establecimiento el día de entrada. Al realizar la reserva a través de nuestra página web, no es necesario que presentes ningún tipo de factura de pago, ni ningún otro documento, ya que lo único que exige el hotel es dicho bono de confirmación de la reserva, junto con tu DNI, o pasaporte titular de la reserva."
    },{
        "Question":"¿Qué hago si el hotel contratado no tiene constancia de mi reserva?",
        "Answer":"Si se diera el caso de que el hotel contratado no tuviera constancia de la reserva realizada, contacta con nosotros telefónicamente. Solo tendrás que indicarnos el localizador de tu reserva y procederemos a resolver inmediatamente la incidencia."
    },{
        "Question":"¿Cuáles son los horarios habituales para la entrada y la salida en los hoteles?",
        "Answer":"En la mayoría de los hoteles, el horario internacional de entrada es a partir de las 15h y la salida entre las 11h y las 12h de la mañana, pero algunos establecimientos pueden modificar esta norma. Consulta las condiciones en la página de información del establecimiento dentro de nuestra web, y muy especialmente las condiciones asociadas a tu tarifa en el momento de realizar la reserva.El horario más habitual de entrada en los apartamentos está estipulado a partir de las 17h, siendo la salida antes de las 10h. El horario de oficina para la recogida de llaves es habitualmente de 17h a 20h. No obstante, algunos establecimientos pueden modificar estos horarios. Consulta las condiciones recogidas en la página del establecimiento en nuestra web y recuerda verificar el horario directamente con la Recepción del establecimiento.Algunos establecimientos (más frecuentemente los apartamentos, aunque no exclusivamente ellos) pueden requerir en el momento de efectuar la reserva o durante la estancia, un depósito y/o fianza. Esta medida de precaución es por daños ocasionales y podrá ser llevada a cabo mediante tarjeta de crédito. Será reembolsado el día de la salida, una vez efectuada la comprobación de que no ha sido ocasionado ningún desperfecto.Puede darse la circunstancia de que el cliente que finaliza su estancia y el que la comienza coincidan en el horario. Ante esta situación, el cliente que va a realizar su entrada deberá conceder un margen de tiempo hasta la preparación de su alojamiento. Dicha situación podrá darse con más probabilidad en temporadas de alta ocupación."
    },{
        "Question":"¿Tengo que añadir a los niños o bebés en la reserva?",
        "Answer":"Sí, es necesario incluir a TODAS las personas físicas que vayan a hacer uso de la estancia en el hotel contratado, independientemente de que sea un bebé, un niño o un adulto.Esto es importante para que el establecimiento pueda prever las personas que se van a alojar, así como las edades de los ocupantes, ya que hay algunos tipos de habitación en las cuales, por la disposición de la misma o normativa legal, no sería posible añadir una cama extra o una cuna para el bebé."
    },{
        "Question":"¿Tengo que avisar si llevo mi propia cuna, o si necesito una para mi estancia en el hotel?",
        "Answer":"Sí, en ambos casos deberás contactar con nuestro Contact Center - Asistencia para que notifique al establecimiento que vas a llevar tu propia cuna o solicitarles que sean ellos quienes te proporcionen una. Recuerda que la solicitud de cuna es solo una petición que deberá ser confirmada previamente por parte del establecimiento y puede suponer un coste adicional. El pago se realizaría directamente en el establecimiento."
    },{
        "Question":"¿Qué diferencia hay entre las distintas pensiones alimenticias?",
        "Answer":"Si tu reserva incluye pensión alimenticia, deberás tener en cuenta que, por lo general, no incluye las bebidas salvo que se indique expresamente, por lo que deberán ser abonadas directamente en el establecimiento.El establecimiento puede modificar sin previo aviso el servicio de comidas, por ejemplo, según el día de la semana o por motivos de ocupación. Por lo general, la media pensión consiste en desayuno y cena, pero puede variar en función del establecimiento, por lo que deberás confirmarlo directamente con éste. Si por causas de retraso, sea cual fuese, se perdiera algún servicio de restaurante correspondiente a la pensión alimenticia contratada, no existirá derecho a devolución. Los pasajeros alojados gratuitamente en camas supletorias o cunas podrían no tener incluido el régimen alimenticio, siendo éste en muchos casos de pago directo en el hotel.Consulta otras condiciones relacionadas con las pensiones alimenticias directamente con nuestro Contact Center – Asistencia. No es posible realizar cambios en las reservas para modificar el régimen alimenticio incluido.Así mismo, para un mayor detalle sobre los tipos de pensiones alimenticias, el significado de las mismas.Estas siglas indican el régimen alimenticio contratado:    • SA: Solo alojamiento.    • AD o HD: Alojamiento y desayuno.    • MP: Media pensión, es decir, desayuno y, generalmente, la cena.    • PC: Pensión completa, es decir, desayuno, almuerzo y cena. Recuerda que, por lo general, las bebidas no están incluidas.    • TI: Todo incluido, es decir, los servicios de PC más los especificados en cada caso.    • SP: Según programa (a consultar con el propio establecimiento).    • HM: Primer día solo alojamiento, segundo día media pensión y, el tercero, desayuno. Esta combinación suele darse en paquetes de nieve o escapadas de fin de semana: viernes a domingo."
    },{
        "Question":"¿Puedo llevar mi mascota al hotel reservado?",
        "Answer":"Solo podrás llevar tu mascota en caso de que así se indique expresamente en el apartado “Servicios y condiciones” que encontrarás en la ficha del establecimiento dentro de nuestra web. Se trata de un servicio especial que ofrecen algunos hoteles y que a menudo consiste en la admisión de animales domésticos de compañía (generalmente, perros). Este servicio suele conllevar el pago de un suplemento en el hotel. Recuerda reconfirmar las condiciones de admisión de animales marcadas por el establecimiento (tipo y/o raza, peso, presentación de la cartilla de vacunación, etc.) en el momento de efectuar la reserva. Deberás tener en cuenta que, pese a estar permitidos, los animales pueden tener limitada su presencia en determinadas zonas del establecimiento. En cualquier caso, la aceptación de estos quedará siempre sujeta a aceptación por parte del establecimiento."
    },{
        "Question":"¿Cómo puedo reservar una plaza de parking o garaje en el hotel?",
        "Answer":"Una vez efectuada tu reserva de hotel, contacta directamente con el establecimiento para consultar la disponibilidad de plaza de parking o garaje. Estas plazas son limitadas por lo que te recomendamos que trates de efectuar reserva previa si el establecimiento lo permite. El pago de este servicio se realizará directamente en el establecimiento."
    },{
        "Question":"¿Tengo que pagar tasas turísticas o están incluidas en el precio del hotel?",
        "Answer":"Recuerda que algunos destinos requieren el pago de la llamada “Tasa turística”, “Tasa local” o similar (\"Ecotasa\", \"Tasa por la prestación de servicios adicionales\", etc). Se trata de recargos que cobra el hotel en destino y que, normalmente, no están incluidos en el importe indicado como precio de la tarifa de alojamiento en nuestra web sino que se paga directamente en el establecimiento reservado. En caso de que tu reserva esté sujeta a dicha tasa y ésta sea de pago directo en el hotel, nuestra web procurará informarte de ello en el apartado “Condiciones de la reserva” durante el proceso de reserva. En el caso excepcional de las reservas de hotel en Nueva York, nuestro precio, en la mayoría de los casos, ya incluye el importe de la tasa y no tendrás que abonarlo en el establecimiento en destino. Sin embargo, es muy importante CONFIRMARLO antes del viaje."
    },{
        "Question":"¿Puedo modificar mi reserva de hotel? ¿Y ampliar o reducir mi estancia una vez en destino?",
        "Answer":"Sí, es posible realizar modificaciones en tu reserva de hotel, incluso si te encuentras ya alojado en él disfrutando de tu estancia. Para ello, contacta con nuestro Contact Center - Asistencia llamando al teléfono que aparece en la parte superior de nuestra web. No obstante, recuerda que se aplicará la política de modificación de reservas indicada en el epígrafe “Política de cambios y cancelaciones” indicada en las condiciones generales."
    },{
        "Question":"¿Qué gastos de cancelación o modificación tiene mi reserva de hotel?",
        "Answer":"Los únicos gastos de cancelación de tu reserva de hotel serán los que aplique el propio establecimiento, si fuera el caso. Podrás consultar su política de cancelación en el momento de efectuar la reserva, tanto si la realizas por la web como telefónicamente. El coste de modificación de reservas de hotel será de 10€ por reserva. Estos gastos se aplicarán con independencia del momento en que se solicite el cambio o la cancelación de la reserva.Si necesitas realizar cambios o modificaciones en tu reserva de hotel, contacta con nosotros llamando al teléfono que aparece en la parte superior de nuestra web. No obstante, los clientes pueden contratar el seguro de viajes PREMIUM que además de las coberturas de viaje cubre los gastos de cancelación y modificación de Viajes El Corte Inglés y los gastos de anulación del proveedor hasta un máximo de 600€. Más información en el apartado “Seguros de viaje” de nuestras Condiciones Generales."
    },{
        "Question":"¿Qué hago si no recibo la confirmación de mi reserva de hotel?",
        "Answer":"Lo primero que puedes hacer es verificar que el e-mail de confirmación no se encuentra en la carpeta de “correos no deseados” de tu cuenta de e-mail. Si no está ahí, contacta con nuestro Contact Center - Asistencia llamando al número que aparece en la parte superior de nuestra web para verificar que la reserva está correctamente realizada y enviarte una nueva confirmación de reserva. Te recomendamos que no realices una nueva reserva sin contactar con nosotros previamente."
    },{
        "Question":"¿Cómo puedo financiar mi reserva de hotel?",
        "Answer":"Si deseas financiar el pago de tu reserva de hotel deberás efectuar la reserva en la web con tu Tarjeta de Compra El Corte Inglés. Las opciones de financiación, como los plazos, dependerán del importe de tu compra, considerando que existe una cuota mínima mensual que se indicará en la web durante el proceso de compra. También te informaremos, antes de realizar la compra, de las condiciones detalladas de financiación a las que la operación quedará sujeta. Recuerda, esta “Fórmula personal de financiación” es solo para clientes con Tarjeta de Compra El Corte Inglés. Consulta condiciones de financiación durante el proceso de compra. Toda la financiación publicitada en esta página es ofrecida por Financiera El Corte Inglés E.F.C., S.A. y está sujeta a su aprobación. Consulta condiciones en https://www.viajeselcorteingles.es/financiacion-online"
    }
]
TALK_TO_HUMAN = [
            {
                "Question": "Pudo Hablar con una persona real?",
                "Answer": "Por Supuesto, envíe su pregunta"
            }, 
            {
                "Question": "Can I talk to a Person?",
                "Answer": "Yes of Course, sout yourself"
            }, 
            {
                "Question": "Can I talk to a human?",
                "Answer": "Yes of Course, sout yourself"
            }
        ]